insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('19320 Lukken Parkway', '2019-10-15 23:08:29', 'Function-based', 'https://robohash.org/vitaequieligendi.jpg?size=50x50&set=set1', 'Gigaclub', 'Kookaburra, laughing', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Devil Rides Out, The', 47);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('9168 Crowley Avenue', '2019-08-15 15:38:47', 'middleware', 'https://robohash.org/quibusdamvoluptatema.jpg?size=50x50&set=set1', 'LiveZ', 'African clawless otter', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Tulpan', 4);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('52 Sutteridge Pass', '2019-10-29 21:15:23', 'Open-architected', 'https://robohash.org/nequevoluptatibuset.png?size=50x50&set=set1', 'Innotype', 'White spoonbill', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Love in Bloom', 6);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('77753 Lighthouse Bay Court', '2019-08-25 20:45:20', 'Right-sized', 'https://robohash.org/liberoofficiaquia.bmp?size=50x50&set=set1', 'Demizz', 'Galapagos mockingbird', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Notti bianche, Le (White Nights)', 20);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('3303 Dayton Park', '2020-01-13 21:34:11', 'Cross-group', 'https://robohash.org/inciduntipsaplaceat.bmp?size=50x50&set=set1', 'Oyoba', 'Potoroo', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Shenandoah', 18);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('07 Thompson Avenue', '2019-06-11 23:44:53', 'Grass-roots', 'https://robohash.org/aliquidnatusaspernatur.jpg?size=50x50&set=set1', 'Fivechat', 'Bustard, denham''s', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Goodbye, Mr. Chips', 8);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('53892 Hansons Avenue', '2019-04-02 14:19:22', 'Open-architected', 'https://robohash.org/sedrerumpossimus.jpg?size=50x50&set=set1', 'Chatterbridge', 'Three-banded plover', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'People Will Talk', 11);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('96853 Muir Drive', '2019-09-01 01:53:02', 'archive', 'https://robohash.org/velitautquas.jpg?size=50x50&set=set1', 'Buzzbean', 'King cormorant', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Return of Frank James, The', 14);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('41690 Maywood Junction', '2019-09-18 18:34:56', 'Grass-roots', 'https://robohash.org/doloribusessecorrupti.jpg?size=50x50&set=set1', 'Shuffledrive', 'Cape wild cat', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Monsters vs Aliens: Mutant Pumpkins from Outer Space', 25);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('7 Green Terrace', '2019-12-31 09:52:26', 'Profit-focused', 'https://robohash.org/iustooccaecatised.bmp?size=50x50&set=set1', 'Browsezoom', 'Greylag goose', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Damned United, The', 50);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('96546 Tomscot Way', '2019-04-11 10:13:45', 'Decentralized', 'https://robohash.org/repudiandaeaccusamuseius.bmp?size=50x50&set=set1', 'Linklinks', 'Burmese black mountain tortoise', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Princess Caraboo', 14);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('41 Helena Pass', '2019-02-13 18:56:01', 'national', 'https://robohash.org/velitestquo.bmp?size=50x50&set=set1', 'Photobug', 'Lemming, collared', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Murder of Crows, A', 19);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('183 Bayside Lane', '2019-08-09 03:02:41', 'asynchronous', 'https://robohash.org/vitaeetsaepe.png?size=50x50&set=set1', 'Vinder', 'Eastern indigo snake', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'To.get.her', 15);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('45450 Dovetail Drive', '2020-01-08 13:24:27', 'multi-tasking', 'https://robohash.org/delectusperspiciatisarchitecto.jpg?size=50x50&set=set1', 'Topicware', 'Dragonfly, russian', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Vanishing, The', 20);
insert into events (address, date_time, details, images, location, notes, summary, title, vol_limit) values ('530 Hollow Ridge Junction', '2019-06-25 17:48:32', 'Reduced', 'https://robohash.org/rerumipsamet.bmp?size=50x50&set=set1', 'Izio', 'Cape raven', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Starship Invasions', 43);

insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Antelope ground squirrel', '391 Northland Junction', 'lbernth0@free.fr', 'https://robohash.org/verocumnulla.png?size=50x50&set=set1', true, 'Lindie Bernth', 'TQh6MJ52RJ79', '602-166-1170', 'http://opensource.org/lobortis/ligula/sit.jsp');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Miner''s cat', '8461 Farmco Road', 'tjee1@guardian.co.uk', 'https://robohash.org/animiaccusamusat.jpg?size=50x50&set=set1', true, 'Teador Jee', 'dtPNACsXCQ1S', '568-743-8658', 'https://themeforest.net/porta/volutpat/quam.xml');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Western palm tanager (unidentified)', '23576 Florence Circle', 'egalland2@youtube.com', 'https://robohash.org/eligendiprovidentnon.png?size=50x50&set=set1', false, 'Ericka Galland', '4gNYhHuju0YV', '278-515-3322', 'http://cnn.com/integer/a/nibh/in/quis.html');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Common eland', '6 8th Trail', 'mgailor3@ted.com', 'https://robohash.org/utplaceatinventore.png?size=50x50&set=set1', false, 'Maurits Gailor', '5Atd4EO5dEwn', '273-373-1995', 'http://va.gov/quam/sollicitudin/vitae/consectetuer/eget.json');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Catfish, blue', '71537 Reindahl Junction', 'rmunnis4@bluehost.com', 'https://robohash.org/facerereprehenderitdeleniti.bmp?size=50x50&set=set1', true, 'Ricard Munnis', 'oloFDb', '214-299-8094', 'http://spiegel.de/metus.json');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Tasmanian devil', '9 Hollow Ridge Road', 'dmarieton5@bloglovin.com', 'https://robohash.org/eosquiain.png?size=50x50&set=set1', true, 'Darrin Marieton', 'Q0QocTLZ3XG', '523-305-9025', 'https://cbc.ca/mi/in.html');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Long-necked turtle', '8 Northfield Junction', 'qingray6@discovery.com', 'https://robohash.org/maioresdolorequi.png?size=50x50&set=set1', true, 'Quinton Ingray', 'IS2I712Oqx4P', '669-980-9723', 'http://wikipedia.org/faucibus/orci/luctus/et/ultrices/posuere/cubilia.aspx');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Genet, small-spotted', '96697 Sloan Point', 'lkippax7@geocities.com', 'https://robohash.org/maximeearumcommodi.png?size=50x50&set=set1', false, 'Lemar Kippax', 'v3knit6ky', '524-874-7472', 'https://census.gov/mi/nulla/ac/enim/in/tempor.json');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Seal, common', '86 Raven Parkway', 'sklimochkin8@google.com.br', 'https://robohash.org/quiearumcorrupti.bmp?size=50x50&set=set1', true, 'Sloan Klimochkin', '7rsNRjQ2YS', '350-560-8749', 'http://zimbio.com/tortor/id/nulla/ultrices.jpg');
insert into users (about, address, email, image, is_org, name, password, phone, website) values ('Gray heron', '9832 Delladonna Street', 'mtippler9@multiply.com', 'https://robohash.org/sedeiusaut.jpg?size=50x50&set=set1', true, 'Maureene Tippler', 'aFJ87vgOs3', '617-392-8409', 'https://webnode.com/congue/diam/id/ornare/imperdiet.png');

